services:
  minio:
    image: minio/minio
    command:
      - server
      - /data
      - --console-address
      - :19001
    ports:
      - 19000:9000
      - 19001:19001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: asdfasdf
  createbuckets:
        image: minio/mc
        depends_on:
          - minio
        entrypoint: >
          /bin/sh -c "
          sleep 5;
          /usr/bin/mc config host add default http://minio:9000 admin asdfasdf;
          /usr/bin/mc rm -r --force default/tergum-backups;
          /usr/bin/mc mb default/tergum-backups;
          /usr/bin/mc policy default myminio/tergum-backups;
          exit 0;
          "
