Meta:
  SchemaVersion: 3
Backups:
  - ID: example-single-file
    Source:
      SingleFile:
        Path: tmp/single-file.in
    Targets:
      - ID: filepath
        FilePath:
          Path: tmp/single-file.out
