version: "3.8"
services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - 21000-21010:21000-21010
    volumes:
      - ./:/ftp/foo:ro
    environment:
      USERS: "foo|bar"
      ADDRESS: 127.0.0.1
